dist: bionic
language: go

go:
  - release
  - tip

branches:
  only:
  - staging
  - master

stages:
  - test
  - build

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go test -v
  - go build -v