os: linux
dist: bionic
language: go

go:
  - master
  - tip

branches:
  only:
  - staging
  - master

stages:
  - test
  - build

jobs:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false

script:
  - go test -v
  - go build -v